#pragma config(Motor,  port1,           wat,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           ever,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           test,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           test1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           test2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           test3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           test4,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           test5,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           test6,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          test7,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true){

if(vexRT[Btn5D]){
motor[port1] = 127;
motor[port2] = 127;
motor[port3] = 127;
motor[port4] = 127;
motor[port5] = 127;
motor[port6] = 127;
motor[port7] = 127;
motor[port8] = 127;
motor[port9] = 127;
motor[port10] = 127;

}else{

motor[port1] = 0;
motor[port2] = 0;
motor[port3] = 0;
motor[port4] = 0;
motor[port5] = 0;
motor[port6] = 0;
motor[port7] = 0;
motor[port8] = 0;
motor[port9] = 0;
motor[port10] = 0;


}
}

}
